### ISSUE TITLE
Android build with 12.10.x can be installed on older  Android versions

### ISSUE THREAD

**Issue by soemo** [trigger-corp/forge#100]
Hello Antoine,

when we are testing your [v2.10.1beta-1 ](https://trigger.io/docs/current/api/beta_release_notes.html) we realized that we can not install it on older Android versions (< 12)

Is that the expected behavior for the beta?
> The instructions seem to be taken from [here](https://developer.android.com/about/versions/12/overview#targeting). If I can understand correctly, you can only test on emulators with Android 12 image."Note that apps compiled against preview versions of the SDK won't be installable on system images that support the final APIs."

Do you know when the first Android API level 31 is available?

**Comment by antoinevg** [comment]
https://www.tomsguide.com/news/android-12-release-date-beta-phone-list-and-all-the-top-features
