### ISSUE TITLE
iOS app build hangs with "Connection aborted"

### ISSUE THREAD

**Issue by soemo** [trigger-corp/forge#105]
Hello @antoinevg 

Can you please check why since yesterday all the iOS app build stop with the message
> [  ERROR] Something went wrong that we didn’t expect:
[  ERROR] (‘Connection aborted.’, error(54, ‘Connection reset by peer’))

Thanks

**Comment by antoinevg** [comment]
My apologies, the build machine crashed. It should be up and running again now.
