### ISSUE TITLE
Move httpd module into ForgeCore

### ISSUE THREAD

**Issue by antoinevg** [trigger-corp/forge#17]
Given the bugs we're seeing in the wake of Google's latest WebView releases this should no longer be an optional module.

### iOS
- [x] don't scan httpd module even if it's specified in config.json
- [x] Move httpd module into iOS ForgeCore
- [x] new flag: `ios_disable_httpd`
- [x] embed a default localhost certificate 
- [x] migrate build steps

### Android
- [x] don't scan httpd module even if it's specified in config.json
- [x] Move httpd module into Android ForgeCore
- [x] new flag: `android_disable_httpd`
- [x] embed a default localhost certificate 

---

Context:

* https://community.trigger.io/t/android-app-freezes-on-start/986/41

**Comment by flippyhead** [comment]
This had fixed things for 9.0 but we're seeing this return on 9.1
