### ISSUE TITLE
Module update: tabs

### ISSUE THREAD

**Issue by antoinevg** [trigger-corp/forge#22]
- [x] Make tests compatible with built-in httpd on Android -> `forge.tools.getURL()` is problematic
- [x] Android throws null exceptions during a couple of the automated tests
- [x] Merge outstanding pull requests
- [x] Update UIWebView view controller handling to rest of Forge 2.8 behaviours
- [x] iOS 13 SDK breaks ViewController presentation
- [x] iOS 13 SDK crashes on UIWebView File Chooser when using the new UIModalPresentationPopover style
- [x] iOS 13 SDK corrupts presenting viewcontroller when using the UIModalPresentationFullScreen style
- [x] Deprecate `UIWebView` and port module to `WKWebView`
- [x] Memory leak: https://github.com/trigger-corp/trigger.io-tabs/issues/17
- [x] Remove legacy UIWebView files

**Comment by scthi** [comment]
The iOS navigation bar doesn't show up anymore.

**Comment by antoinevg** [comment]
Oops, looks like I didn't copy the module binary over before hitting publish 🤦🏼‍♂️

Thanks for the report!

Can you please force a rebuild and try again?

**Comment by scthi** [comment]
This works now thanks.

But there is another thing: on iOS 12.4. the app becomes black after closing a tab.
I'm not sure if this is a tabs or a platform issue...

<details>
<img alt="black-after-tab-close" src="https://user-images.githubusercontent.com/318533/64941361-b5362880-d866-11e9-861a-e5e84e4c2353.gif" />
</details>

**Comment by antoinevg** [comment]
Xcode 11 GM issue. Hopefully Apple settles on a consistent set of behaviours for `UIModalPresentation*` before they ship the iOS 13 GM. :-P

Can you please try again with tabs `v3.1`?
