### ISSUE TITLE
Android 29 SDK breaks native element layouts

### ISSUE THREAD

**Issue by antoinevg** [trigger-corp/forge#23]
- [x] statusbar not visible
- [x] always pin webview to top of display  - use `viewport-fit=auto` OR `safe-area-inset-*` to position in relation to statusbars / navigation bars
    * Use `var(--safe-area-inset-*)`
- [x] Deprecate `adjust_content_insets` 
    * Set in config.json: `android.viewport_fit = auto | cover`
- [x] Deprecate`forge.layout.setContentInsetAdjustmentBehavior` if possible

**Comment by marwonline** [comment]
Hi, I currently still have problems with the `--safe-area-inset` CSS variables on Android 10.

- Trigger Version:  v2.8.1alpha-5
- Phones: Pixel 3a and One+6
- Android: 10 /API level 29
- "viewport_fit": "cover" in config and html meta 

The forge call for `layout.getSafeAreaInsets` returns for the first call a top inset of 11px and for all subsequent calls it reduces down to 0.00005px. Still 11px is not correct. The trigger version 2.7 returned 24px.

The CSS variable `--safe-area-inset-top` is set but only has a value of 4.36756px which is also not correct. 

Did I miss anything to configure?

**Comment by antoinevg** [comment]
Ideally you should be able to get by with just css now and drop `layout.getSafeAreaInsets` entirely. 

That said:

1. There was indeed a bug where `layout.getSafeAreaInsets()` was reducing on subsequent values. I always forget that Java assigns by reference rather than value! 🤦🏼‍♂️
1. There has been a semantic change to the insets to bring us in line with the browser-based html/css behaviours. Previously I think we used to include nav bars etc. in the inset size - now we automatically offset the webview to account for it and just return the offset for any notches.
1. There's plenty of weirdness from Android 10 itself where I'm getting sizes that are off by fractions of a pixel. I'm not entirely sure what to do about that yet.

I've pushed some changes, can you try forcing a rebuild against v2.8.1alpha-5?

I've also added a bit more info to Step 4 of the migration guide: https://trigger.io/docs/current/api/migration_guide_27_to_28.html

Any code snippets or screenshots are welcome too!

**Comment by marwonline** [comment]
I'm using the snippet from the migration guide now `var(--safe-area-inset-top);` and enabled the flag `ios_also_set_css_safe_area_inset_env_as_var`.

Currently it works on both Android 10 phones and on the iOS13 on a iPhone7. 

Thanks for the fast fix 👍 


PS: Looks like a typo in the documentation: https://trigger.io/docs/current/api/migration_guide_27_to_28.html  -> Step 4  -> you two times wrote `core.android.adjust_content_insets`

**Comment by marwonline** [comment]
I've found another issue with Android 5. 

Same setup as above.  (Chrome 76.x)
Using `var(--safe-area-inset-top);` but I only get `0px`

**Comment by antoinevg** [comment]
Hrrm… it may be that the older Android's either don't support CSS `var` lookups or don't allow setting them via Javascript.

What happens if you do something manual like:

    body {
        --safe-area-inset-top: 100px;
        padding-top: var(--safe-area-inset-top);
    }

That said you should still be okay, there aren't any earlier than Android 9 devices in the real world that have notches or safe area insets - Google only introduced it in the last release.

**Comment by marwonline** [comment]
I'm trying to work around the status bar at the top. 
As the following setup works fine I assume that the variables are supported.
```
: root {
   --custom-safe-area-inset-top: 24px
}
html {
  padding-top: var(--custom-safe-area-inset-top);
}
```

I debugged this and I always get `0px` in the `--safe-area-inset-top` CSS property and for the deprecated `layout.getSafeAreaInsets()` too. 

Device: Samsung S4
OS: Android 5.0

**EDIT**
Same behaviour on Android 6 on Samsung S5

**Comment by antoinevg** [comment]
You should never get a safe area inset value other than 0.0 on devices earlier than Android 9.0 as far as I understand as safe area insets only came into existence after Android 9!

If there's a problem with the status bar overlapping the webview it's more likely that this is because either the particular device, Android 5 or its WebView isn't doing layout correctly.
 
Can you post some screenshots of the Android 5 issue as long as well as what it's looking like on a working version of Android?

If you can post some HTML/CSS I can use to try reproduce it on an emulator on this side that can also help.

Worst case you may have to do some device detection and/or manual workarounds to get things working on that device.

**Comment by marwonline** [comment]
Previously with the forge version `v2.7.6` we got a safe area inset. API level 23. See the screenshot from catalyst:
 
![Screenshot 2019-09-11 at 10 20 22](https://user-images.githubusercontent.com/25180025/64680357-ecc75e00-d47d-11e9-873f-a999ed33bc43.png)

**Comment by antoinevg** [comment]
Yeah I know, but this is what I was talking about when I said we've changed the semantics to match what the browser implementations are doing.

If you can give me the screenshots I asked for and something I can use to reproduce on my side I can see if this is something you'll have to workaround on your end or whether I can hack around it on my end.

**Comment by marwonline** [comment]
Okay ..  here a minimal snipped:

```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no, viewport-fit=cover" />
  <title>The title</title>

  <style type="text/css">
    :root {
      --custom-safe-area-inset-top: var(--safe-area-inset-top);
    }
    html {
      height: 100vh;
      width: 100vw;
    }
    body {
      padding-top: var(--safe-area-inset-top);
      border: 1px solid red;
      margin: 0;
    }
    div {
      border: 1px dashed green;
    }
  </style>
</head>
<body>
<div>Some nice text!1!<br/>More text</div>

<script>
  var supportCssVar = window.CSS.supports('padding-top: var(--custom-safe-area-inset-top)');
  console.log('CSS var support: ', supportCssVar);
  window.forge.internal.call('layout.setStatusBarTransparent', {transparent: false});
  window.forge.launchimage.hide();
</script>
</body>
</html>

```
And the screen shot: 

<details>

![screenshot-1568192593213](https://user-images.githubusercontent.com/25180025/64683695-12576600-d484-11e9-8efd-b25d34af5245.jpg)

</details>

EDIT: hiding the screen shot

**Comment by antoinevg** [comment]
Tx! Can you please also add a screenshot from a device where this layout works?

From what I can see so far this does look like a layout bug on Android 5's side. 

On Android, irrespective of what viewport-cover is set to the WebView is supposed to be placed so that the top is aligned to the bottom of the status bar, not the top of the screen.

**Comment by marwonline** [comment]
Sry my fault. The snippet does not work on Android 10. I'll update the snippet and come back.

**Comment by antoinevg** [comment]
Do you perhaps have the status bar set to transparent? :-)

I'm not even sure why we still have that as an option as it hasn't been part of a modern Android look & feel for a very long time.

Can you try a:

    forge.internal.call("layout.setStatusBarTransparent", {
        "transparent": false
    }, function () {
        // pass
    });

…and let me know if you still see the issue?

**Comment by marwonline** [comment]
Indeed. The status bar was transparent. Now without it the versions still differ. (I updated the snippet above.)

left Pixel 3a with Android 10
right Samsung S5 with Android 6.0.1

v2.8.1beta-1
![IMG_20190911_134109](https://user-images.githubusercontent.com/25180025/64695274-07103480-d49c-11e9-9927-4e4f481e4ae7.jpg)

v2.7.6
![IMG_20190911_134459](https://user-images.githubusercontent.com/25180025/64695276-07a8cb00-d49c-11e9-8f5b-e9e0b25a2e90.jpg)

**Comment by antoinevg** [comment]
Drat, I don't have a Galaxy S5 here and I'm having issues reproducing this on the Android Emulator:

![Screenshot 2019-09-11 at 14 26 35](https://user-images.githubusercontent.com/44808/64697977-45a8ed80-d4a2-11e9-9889-b6277102e6e2.png)

AVD: Samsung Galaxy S5 Android 6.0 (Emulator)

This may be because:

1. The issue only shows up on 6.1 and the emulator only has Android 6.0 available.
2. This only shows up on the Samsung Galaxy S5 hardware
3. This only shows up on Samsung's versions of Android

Not the first time that Samsung has given us this kind of weirdness :-)

Do you have any other devices handy that show the bug? Can you please give me a list of hardware & Android versions if you do?

This is all the testing hardware available to me on this side:

![IMG_0021](https://user-images.githubusercontent.com/44808/64697956-404ba300-d4a2-11e9-9dcf-9bfe3d416fd9.jpg)

From left to right:

* Android 6.0: Alcatel 4034x
* Android 6.0: Sony F3311  
* Android 7.0: RedMi Note 4
* Android 9.1: Huawei p30 lite 
* Android 10.0: Essential PH-1

**Comment by antoinevg** [comment]
Also (and this is a long shot!) can you please try building against `v2.8.1beta-2` and see if it makes any difference?

**Comment by antoinevg** [comment]
To eliminate any potential red herrings can you please also attach the `src/config.json` you're using for your test app.

**Comment by marwonline** [comment]
With `v2.8.1beta-2` now only the Samsung devices are misaligned.

```    
   "android": {
      "minimum_version": "19",
      "disable_ics_acceleration": true,
      "package_name": "%android_package_name%",
      "viewport_fit": "cover"
    }
```

![IMG_20190912_095618](https://user-images.githubusercontent.com/25180025/64767929-ea7e0600-d548-11e9-8981-354a16b607b9.jpg)

Left to right

- Android 8.0 - Sony G3121
- Android 8.0 - Huawei P20 lite
- Android 10 - Pixel 3a 
- Android 6.0.1 - Samsung Galaxy S5 (broken)
- Android 10 - OnePlus 6
- Android 5.0.1 - Samsung Galaxy S4 (broken)

**Comment by antoinevg** [comment]
Cool, thank you muchly Martin!

So at this stage it looks like this is localised specifically to older Samsung hardware rather than Android.

Do you have access to any non-Samsung hardware running Android 5 or 6 so we can be sure?

I remember the Galaxy devices having an issue with the status bar layout many years ago - there was a workaround we had to use until Google eventually fixed it in a newer version of the Android SDK. So this looks like a regression of that earlier bug. Of course the earlier workaround no longer works either :-)

Can you please attach the entire config.json for your test app?

**Comment by marwonline** [comment]
> Do you have access to any non-Samsung hardware running Android 5 or 6 so we can be sure?

Unfortunately I've no native Android 5.0 and 6.0 devices besides the Samsungs. I tried both Android version in the simulator and there it works fine.

Here the full file. (There are still some placeholders left. )

<details>

```
{
  "config_version": "4",
  "name": "%name%",
  "author": "%author%",
  "version": "%version%",
  "platform_version": "v2.8.1beta-2",
  "core": {
    "general": {
      "logging": {
        "level": "INFO"
      },
      "reload": true,
      "trusted_urls": ["https://localhost/*"],
      "httpd": {
        "port": 9360,
        "url": "https://localhost:9360/src/index.html",
        "certificate_path": "localhost.p12",
        "certificate_password": ""
      }
    },
    "android": {
      "minimum_version": "19",
      "disable_ics_acceleration": true,
      "package_name": "%android_package_name%",
      "viewport_fit": "cover"
    },
    "ios": {
      "device_family": "any",
      "package_name": "%ios_package_name%",
      "disable_web_storage_backup": true,
      "webview": "WKWebView"
    }
  },
  "flags": {
    "migrate_web_storage_for_webview": %enable_storage_migration%,
    "move_filescheme_storage_to_httpscheme": %enable_storage_migration%,
    "android_workaround_transparent_statusbar_keyboard_bug": true,
    "ios_also_set_css_safe_area_inset_env_as_var": true
  },
  "modules": {
    "contact": {
      "version": "2.12",
      "config": {
        "usage_description": "Allow access to your contacts in order to recommend the app."
      },
      "disabled": %disable_recommend_module%
    },
    "icons": {
      "version": "2.9",
      "config": {
        "android": {
          "48": "img/native/android/icon-48.png",
          "72": "img/native/android/icon-72.png",
          "96": "img/native/android/icon-96.png",
          "144": "img/native/android/icon-144.png",
          "192": "img/native/android/icon-192.png",
          "adaptive": {
            "108": "img/native/android/icon-47.png",
            "162": "img/native/android/icon-70.png",
            "216": "img/native/android/icon-93.png",
            "324": "img/native/android/icon-140.png",
            "432": "img/native/android/icon-186.png",
            "background-color": "%android_adaptive_icon_background-color%"
          }
        },
        "ios": {
          "57": "img/native/ios/icons/icon-57.png",
          "72": "img/native/ios/icons/icon-72.png",
          "76": "img/native/ios/icons/icon-76.png",
          "114": "img/native/ios/icons/icon-114.png",
          "120": "img/native/ios/icons/icon-120.png",
          "144": "img/native/ios/icons/icon-144.png",
          "152": "img/native/ios/icons/icon-152.png",
          "167": "img/native/ios/icons/icon-167.png",
          "180": "img/native/ios/icons/icon-180.png",
          "1024": "img/native/ios/icons/icon-1024.png",
          "prerendered": true
        }
      }
    },
    "launchimage": {
      "version": "2.13",
      "config": {
        "android": {
          "portrait": "img/native/android/launchimage.png",
          "landscape": "img/native/android/launchimage.png",
          "background-color": "%android_launchimage_background-color%",
          "background-size": "%android_launchimage_background-size%"
        },
        "ios": {
          "wC_hC": "img/native/ios/launchimages/iphone-compact-landscape.png",
          "wR_hC": "img/native/ios/launchimages/iphone-landscape.png",
          "wC_hR": "img/native/ios/launchimages/iphone-portrait.png",
          "wR_hR": "img/native/ios/launchimages/ipad-landscape.png"
        },
        "hide-manually": true
      }
    },
    "display": {
      "version": "2.11",
      "config": {
        "statusbar": {
          "android": {
            "transparent": true
          },
          "ios": {}
        },
        "orientations": {
          "ipad": "any",
          "android": "any",
          "iphone": "portrait"
        }
      }
    },
    "file": {
      "version": "2.24",
      "config": {
        "usage_description": "Allow access in order to upload pictures and videos to the app."
      },
      "disabled": %disable_file_module%
    },
    "capture": {
      "version": "2.24",
      "config": {
        "usage_description": "Allow access in order to upload pictures and videos to the app."
      }
    },
    "notification": {
      "version": "2.8",
      "config": {}
    },
    "bolts": {
      "version": "1.9.0",
      "config": {}
    },
    "urlhandler": {
      "version": "2.2",
      "config": {
        "scheme": "xxxxxxxxxx"
      }
    },
    "request": {
      "version": "2.11",
      "config": {}
    },
    "share": {
      "version": "1.3",
      "config": {}
    },
    "prefs": {
      "version": "2.2",
      "config": {}
    },
    "browsersettings": {
      "version": "1.6",
      "config": {
        "accept_cookies": true,
        "media_playback": {
          "inline_video": false,
          "autoplay_video": true,
          "enable_html5_audio": true,
          "enable_background_audio": false,
          "respect_playing_audio": true
        }
      }
    },
    "utils": {
      "version": "0.67",
      "config": {
        "initialStatusBarStyle": "light_content"
      }
    },
    "platform": {
      "version": "2.3",
      "config": {}
    }
  }
}
```

</details>

PS: do you have an idea how to correctly handle the padding with a transparent status bar? 

EDIT: Collapsed the JSON file

**Comment by antoinevg** [comment]
Tx!

I've implemented a workaround hardcoded specifically for the Galaxy S4/5 that sets a 24px safe area inset for those devices.

Can you please try rebuild against `v2.8.1beta-2`  again and see if that helps? (you may need to force a rebuild)

You should see a log message output in this platform version that begins with `Hey Martin! I'm an Android …` 

Can you please forward me those messages for the Galaxy S4 and S5 devices? :-)

re: _Transparent Status Bars on Android_

I'm making the call that transparent status bars are no longer going to be supported on Android moving forward because:

1. There is no longer anything resembling consistency between what "transparent" means on different Android versions & devices. Some have a translucent effect, some just remove the status bar background, some do nothing and some just replace it with a weird unusable drop shadow (wtf Sony?).
1. Modern Android apps are no longer using it as part of their look&feel.

We may, at some future point, add support for iOS-style blurred-translucency if Google move the implementations they're using for their own apps into the standard SDK.

I'll be removing API support before the final v2.8.1 release.

**Comment by marwonline** [comment]
Sry, I'm on a conference for the next days. I'll check this out on Monday.

**Comment by marwonline** [comment]
Seems to work on all my test devices now. Here are the logs:

From the S5:
```
09-16 09:15:18.943  7734  7734 I Forge   : Hey Martin! I'm trying to work around the bug because I'm an Android 23 device, my manufacturer is: |samsung| and my model is: |SM-G900F|
```

From S4
```
I/Forge   (31666): Hey Martin! I'm trying to work around the bug because I'm an Android 21 device, my manufacturer is: |samsung| and my model is: |GT-I9505|
```

**Comment by antoinevg** [comment]
Tx Martin!

**Comment by marwonline** [comment]
Sorry for reporting another glitch. 
I tried the landscape mode with Notch devices. 

On the P20 lite the bar around the notch get's black. On the other devices it remains white. I added the `background-color: blue` to the `html` block. 
For me it looks the old SDK versions WebView also managed the area around the notch and now it does not. (`v2.8.1beta-2`)

From left to right:

- One+6 Android 9.0
- One+6 Android 10.0
- Huawei P20 lite - Android 8.0

![IMG_20190916_131623](https://user-images.githubusercontent.com/25180025/64954087-d574e000-d884-11e9-855e-043a51593f23.jpg)

Non-notch devices are not affected.

**Comment by antoinevg** [comment]
Tx for the report Martin, there are always wrinkles every time iOS & Android do a major version update so this really helps! :-)

This actually looks like its a Huawei issue though. I'd say that they are not reporting their notch metrics correctly to the operating system.

In fact, the P20 came out with Android 8 on it and Google only added notch support in Android 9. That would explain why it won't be able to display content in the notch area.

What's the Android version on the P20 currently?

**Comment by marwonline** [comment]
The P20 lite (Android 8.0.0, EMUI 8.0.0, Patch Level 1st July 2018) on the right side is the only one that looks fine to me. The safe area around the notch is black. 

For me having a white bar around the notch on the One+ devices looks rather ugly.

**Comment by antoinevg** [comment]
Doh! Sorry I thought you'd added those insets.

Let me figure out what's going on, it's probably a bug on my side :-)

**Comment by antoinevg** [comment]
So that escalated quickly. I just spent the last three days rewriting our Android UI layer. 😑 

There are some new limitations imposed by the diversity of layout combinations and Android versions/manufacturers we need to be able to support:

* **All Android versions:** Status Bars are hidden when device is rotated into landscape mode (this mirrors iOS behaviour so I quite like this one)
* **All Android versions:** Status Bars are opaque when `viewport_fit: auto`
* **All Android versions:** Status Bars are opaque when the navigation bar is enabled
* **Android < 28:** Status Bars are always opaque
* **Android >= 28:** Status Bars are transparent for `viewport_fit: cover`

This is a pretty major change so I won't be surprised if there's some weird new breakage. 🙂 

Particular things  to watch out for during testing:

* That Android >= 28 devices with notches from different manufacturers behave the same.
* That everything still plays nicely with `v3.1` of the tabs module.
* That the fix for the Galaxy S4/S5's still works.

If you force a rebuild against `v2.8.1beta-2` it should pick up the changes.

Release notes: https://trigger.io/docs/current/api/beta_release_notes.html

**Comment by marwonline** [comment]
I just re-tested your change on all my Android devices including some tablets. As far for now I could not find any glitch. Thanks for the great work 👍
