### ISSUE TITLE
Cookie gets lost after closing app too fast

### ISSUE THREAD

**Issue by roeder82** [trigger-corp/forge#26]
**Device information:**
 - Hardware: Iphone X
 - Operating System and Version: iOS 12.3
 - Forge Platform version: v2.7.6

**App information:**
```
{
  "config_version": "4",
  "version": "4.0.400",
  "platform_version": "v2.7.6",
  "core": {
    "general": {
      "logging": {
        "level": "INFO"
      },
      "reload": true,
      "trusted_urls": ["http://*/*","https://*/*"]
    },
    "ios": {
      "device_family": "any",
      "package_name": ...,
      "disable_web_storage_backup": true,
      "adjust_content_insets": "never",
      "webview": "WKWebView"
    }
  },
  "flags": {
    "ios_force_wkwebview": true,
    "migrate_web_storage_for_webview": false,
    "move_filescheme_storage_to_httpscheme": false,
    "android_workaround_transparent_statusbar_keyboard_bug": true
  },
  "modules": {
...
    "request": {
      "version": "2.11",
      "config": {}
    },
...
    "httpd": {
      "version": "1.4",
      "config": {
        "port": 9360,
        "url": "https://localhost:9360/src/index.html",
        ...
      }
    },
    "prefs": {
      "version": "2.2",
      "config": {}
    },
    "browsersettings": {
      "version": "1.6",
      "config": {
        "accept_cookies": true,
        "media_playback": {
          "inline_video": false,
          "autoplay_video": true,
          "enable_html5_audio": true,
          "enable_background_audio": false,
          "respect_playing_audio": true
        }
      }
    },
...  }
}
```

**To Reproduce**
1. Set server side cookie A=1 on XHR call (server shows cookie is sent)
2. Set another server side cookie A=2 on XHR call (server shows cookie is sent with any subsequent call)
3. immediately close app
4. reopen app server shows, that cookie value A=1 is sent instead of A=2 

**Expected behaviour**
Persistence of cookie is done right after receiving the value.

**Actual behaviour**
Received Cookie value is not immediately persisted.

**Comment by antoinevg** [comment]
Also see: https://community.trigger.io/t/wkwebview-cookies-on-initial-load/1039

Possibly related:

* https://issues.apache.org/jira/browse/CB-12074
* https://github.com/Telerik-Verified-Plugins/WKWebView/issues/247
* https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/22
* https://bugs.webkit.org/show_bug.cgi?id=177478
* https://bugs.webkit.org/show_bug.cgi?id=200857
