### ISSUE TITLE
Status bar style "darkContent"

### ISSUE THREAD

**Issue by ice8lue** [trigger-corp/forge#29]
**Is your feature request related to a problem? Please describe.**
Before, `forge.layout.setStatusBarStyle` accepted two values, `default` and `light_content` which resulted in black or white status bar text. Now with iOS 13 the `default` mode switched to cause black text in system light mode but white text when system is set to dark mode.

**Describe the solution you'd like**
Apple introduced a new option `darkContent` to UIStatusBarStyle (see [docs](https://developer.apple.com/documentation/uikit/uistatusbarstyle)). It would be nice to have that exposed as `dark_content` to `forge.layout.setStatusBarStyle`, as the other styles already are.

**Comment by ice8lue** [comment]
@antoinevg I tried to fork the `display` module and provide a PR for this, but as far as I can see, the `setStatusBarStyle` method  there only pipes the setting to the internal `layout` component, right? So probably nothing I could help with?

**Comment by antoinevg** [comment]
If you update your platform version to `v2.8.2` and the display module to `2.12` you should have:

`forge.layout.setStatusBarStyle` supports the following values:

* `UIStatusBarStyleLightContent` or `light_content`
* `UIStatusBarStyleDarkContent` or `dark_content`
* `UIStatusBarStyleDefault` or `default`

:-)

**Comment by ice8lue** [comment]
@antoinevg Awesome, thanks for the fast fix =)

Though, I can't get it to work. Also with `forge.display.setStatusBarStyle("dark_content")`, the text still renders white. Also a direct call to `forge.internal.call("layout.setStatusBarStyle", {style: 'UIStatusBarStyleDarkContent'}, success, error)` didn't yield success (also didn't give any feedback about success or failure).

**Comment by antoinevg** [comment]
Working on this side, are you sure you bumped both the module and platform versions? 

That said, on dark mode I'm finding that `UIStatusBarStyleDarkContent` does exactly the same thing as `UIStatusBarStyleDefault` i.e. override the specified behaviour in favour of White Text.

**Comment by antoinevg** [comment]
Fiddlesticks - I left out one required change, holdasec and I'll push it through so we can see if that makes a difference :)

**Comment by antoinevg** [comment]
Okay, that's more like it - if you force a rebuild things should go more to plan this time! 😊

**Comment by ice8lue** [comment]
I'm probably doing something wrong :/

I have forge v2.8.2 and display v2.12. Then, I'm doing this:

```
forge.display.setStatusBarTransparent(true);
forge.display.setStatusBarStyle('dark_content');
```

I did a remote build, still no changes 🤔

**Comment by antoinevg** [comment]
You may be running into a race-condition, it's always better to use the callbacks:

```javascript
forge.display.setStatusBarTransparent(true, function () {
    forge.logging.log("setStatusBarTransparent success");
    forge.display.setStatusBarStyle("dark_content", function () {
        forge.logging.log("setStatusBarStyle success");
    }, function (e) {
        forge.logging.error("setStatusBarStyle error: " + JSON.stringify(e));
    });
}, function (e) {
    forge.logging.error("setStatusBarTransparent error: " + JSON.stringify(e));
});
```

**Comment by ice8lue** [comment]
I tried the above, both success callbacks are called, but the text stays white...

**Comment by antoinevg** [comment]
Some thoughts:

1. Did you change the config.json to force a rebuild?
1. Have you tried with a vanilla forge app?
1. If my memory doesn't play tricks with me I seem to remember a staffbase module at one point that set the statusbar prefs? Is it still included in your builds? Could it be conflicting?
