### ISSUE TITLE
build number per configuration (android:versionCode and iOs CFBundleVersion)

### ISSUE THREAD

**Issue by soemo** [trigger-corp/forge#32]
**Is your feature request related to a problem? Please describe.**

Currently it is not possible to specify the build number (`android:versionCode` and iOs `CFBundleVersion`) in the configuration file when building the `apk` or `ipa` file.

**Describe the solution you'd like**

We would like, just like `author` or `version`, to be able to specify the build number when building the apk and ipa files in the configuration file. Ideally separate for iOS and Android. The timestamp can still be set as fallback( default value). [set_attribute_value_xml to AndroidManifest.xml](https://github.com/trigger-corp/apptentive-trigger-io/blame/91343b526109ade35202d11b1b82ff211d6060d2/forge-workspace/.template/generate_dynamic/customer_phases.py#L329)

**Comment by antoinevg** [comment]
Thank you for the feature request!

If you update to `platform_version: "v2.8.4"` you should now be able to do this:

```javascript
"version": "0.1",
"build_number": {
    "android": "12345678",
    "ios": "123.456.78"
},
```

**A word of warning:** if you're using [Reload](https://trigger.io/reload/) with your app. Reload uses the build number to uniquely identify builds and if you forget to update the build number for new releases it will probably break things!

**Comment by soemo** [comment]
Thank you very much. We'll try it out.

**Comment by soemo** [comment]
Hello, today I finally got the chance to test the build number. First of all thanks again for the quick implementation. Unfortunately the implemented iOS validation does not match our ideas of the build number. I get the error:

`Forge API call to app/707ecebf679343e7921a5925591966ab/build went wrong: 
Value u'2019112600' for field 'ios' does not match regular expression '^\d{,5}(\.\d{,5})?(\.\d{,5})?$'`

Our goal is to have on Android and iOS the same automatic generated build number, e.g.2019112600

I interpreted the information on the page in such a way that you can use only one number without dots. https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion

Do you understand it in the same way?And is it possible to adjust the validation?

**Comment by antoinevg** [comment]
No problem, you're right on the money. It looks like the regex did not match the python regex library! 🤦🏼‍♂️

I've fixed it and, for the sake of consistency, I've also updated the Android version to use a string rather than a number.

This should work now:

```javascript
"version": "0.1",
"build_number": {
    "android": "2019112600",
    "ios": "2019112600"
},
```

**Comment by soemo** [comment]
Thanks, it is working

**Comment by soemo** [comment]
Sorry to hijacked a closed issue. But with the implementation and using of the buildnummer we were facing a strange problem today.

On the Jan 20th we added an app version into our Android beta track 
- versionName: "4.2.000"
- versionCode: 2020012001
Today (Jan 23th) we want to add the app with the same versionName but another (higher) versionCode. It is not working, because for whatever reason in the AndroidManifest.xml we have a wrong (the old) versionCode '2020012001' 
the expected values are:
- versionName: "4.2.000"
- versionCode: 2020012302

AndroidManifest.xml
````
<?xml version="1.0" encoding="utf-8"?>
<manifest
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:versionCode="2020012001"
    android:versionName="4.2.000"
    android:installLocation="0"
    android:compileSdkVersion="29"
    android:compileSdkVersionCodename="10"
    package="com.mitarbeiterapp.android"
    platformBuildVersionCode="29"
    platformBuildVersionName="10">
````

I can find the expected versionCode '2020012302' in the generated app_config.json in the build_number key and in the version_code key

````
{
    "assets_url": null, 
    "author": "xyz", 
    "build_number": {
        "android": "2020012302", 
        "ios": "2020012302"
    }, 
    "config_hash": "acb2c15bd5af02b7b899df3f6a7004b92b38bbe9", 
    "config_version": "4", 
    ...
    "platform_version": "v2.8.4", 
    "trigger_domain": "https://trigger.io", 
    ...
    "version": "4.2.000", 
    "version_code": "2020012302"
````
But why not in the AndroidManifest.xml? With the old (same like the last time) versionCode we can not upload the new build. 

Any idea, why we have the old versionCode in the AndroidManifest.xml

**Comment by antoinevg** [comment]
It's probably because builds are cached and AndroidManifest.xml  is only regenerated after a full rebuild.

An easy way to force a rebuild is to add the `parameters ` module to your app, add a placeholder value and increment it every time you need to invalidate a cached build.

For example:

```
"parameters": {
    "config": {
        "bump_me_to_invalidate_the_build_cache": "7"
    },
    "version": "2.0"
},
```

**Comment by soemo** [comment]
Thanks for the explanation. That means in other words, a change of the version (versionName) triggers a full rebuild, but a change of the build_number (versionCode) not. From my understanding a versionCode change should trigger a full rebuild. Isn't it?

**Comment by antoinevg** [comment]
It's complicated.

In the past version numbers were set on the client-side rather than the server-side.

Then Google wrapped AndroidManifest.xml into a giant ball of obfuscation with the result that it had to be moved server-side.

It may well be that the cache invalidation rules weren't updated to trigger on version changes.

**Comment by soemo** [comment]
Thanks we are using the parameters module approach now.
