### ISSUE TITLE
iOS app build is not working since today

### ISSUE THREAD

**Issue by soemo** [trigger-corp/forge#38]
**Problem:**
As of today we can no longer build an iOS app. 

```
[  DEBUG] 2020-05-19 11:18:58,248 -- running xcode command: "['/opt/xcode/11.3.1/Xcode.app/Contents/Developer/usr/bin/xcodebuild', '-allowProvisioningUpdates', '-sdk', 'iphoneos', '-configuration', 'Release', 'EXECUTABLE_NAME=Forge']"
[  ERROR] 2020-05-19 11:18:59,800 -- Xcode error:
[  ERROR] 2020-05-19 11:18:59,877 -- Build settings from command line:
    EXECUTABLE_NAME = Forge
    SDKROOT = iphoneos13.2
note: Using new build system
note: Planning build
note: Constructing build description
error: There are no accounts registered with Xcode. Add your developer account to Xcode (in target 'ForgeInspector' from project 'ForgeInspector')
error: No signing certificate "iOS Development" found: No "iOS Development" signing certificate matching team ID "XXX" with a private key was found. (in target 'ForgeInspector' from project 'ForgeInspector')
** BUILD FAILED **
[   INFO] 2020-05-19 11:19:00,123 -- cleaning up source directories
[  ERROR] 2020-05-19 11:19:00,123 -- Xcode error
```

Forge Platform version: v2.8.6

Has anything on your side changed or are there any known problems right now?

**Comment by antoinevg** [comment]
Just saw this as well. Current theory is that Apple somehow remotely mass-expired all our build server provisioning certificates a month early?

Please stand by for more info as I dig.

**Comment by antoinevg** [comment]
Fun new behavior: 

Apple will now let you know that you need to sign an updated developer agreement by returning an empty list when Xcode requests your signing certificates.

Builds should be back up now. My apologies for the downtime and please let me know if you run into any further issues!

**Comment by soemo** [comment]
Thanks. It is working now again
