### ISSUE TITLE
White area on bottom of screen on iOS with viewport-fit=cover

### ISSUE THREAD

**Issue by antoinevg** [trigger-corp/forge#39]
**Device information:**
 - Hardware: iPhone Xr
 - Operating System and Version: iOS 13.5.1
 - Forge Platform version: v2.8.6

**To Reproduce**
Please see: https://community.trigger.io/t/white-area-on-bottom-of-screen-on-ios-with-viewport-fit-cover/1057

**Expected behaviour**
In order to fill the whole screen, one should use `viewport-fit=cover` (according to the guides). 

**Actual behaviour**
When making an empty app with `viewport-fit=cover`, an empty white area shows up at the bottom. It seems that the app height does not scale to the full height of the screen:

<img src="https://community.trigger.io/uploads/default/original/1X/476e580028dee32ae87f588f5bc5bb5805a083d5.jpeg" width=320>

After closing the app and opening it again, the height seems to be recalculated and the problem is gone.

The height is also recalculated if the device is rotated.

**Comment by antoinevg** [comment]
For now, the workaround I’ve found that works best is to specify safe-area insets for all page directions:

```
body {
    background-color: yellow;
    padding-top: env(safe-area-inset-top);
    padding-left: env(safe-area-inset-left);
    padding-bottom: env(safe-area-inset-bottom);
    padding-right: env(safe-area-inset-right);
}
```

**Comment by trrichmondreglo** [comment]
Did you found any solution for this issue?
