### ISSUE TITLE
Upload/download support from iFrames

### ISSUE THREAD

**Issue by scthi** [trigger-corp/forge#40]
**Is your feature request related to a problem? Please describe.**

* we are embedding certain 3rd party pages via iFrame
* submitting forms with <input type=file/> is not working in them
* it would be nice if this would work out of the box, since we can't influence the js of these pages

**Describe the solution you'd like**

We provided this functionality for the tabs module some time ago:
https://github.com/trigger-corp/trigger.io-tabs/compare/3eec58ba2e261991214ff181fe63174ed01dc0f1...b89a175480aea0def64af4e92d48592a61e0872f

It would be nice if this could be adapted in the forge core.

**Describe alternatives you've considered**

**Additional context**

**Comment by antoinevg** [comment]
Fixed in: v2.9.1beta-2
