### ISSUE TITLE
Forge build not working

### ISSUE THREAD

**Issue by soemo** [trigger-corp/forge#48]
Hello Antoine,

Since 3 hours hours we have the problem that we can not longer build our app (Android and iOS) using forge.
Is there a known problem?

````
running cd native-android-staffbasePublicStore/ && forge --username xxx --password ######## build android
/bin/sh: 1: forge: not found
[ FAILED]Error: Command failed: cd native-android-staffbasePublicStore/ && forge 
--username xxx --password ######## build android
/bin/sh: 1: forge: not found

Fatal error: this.async is not a function
````
Can you please give us a quick indication of what it could be. We are currently preparing the next big release, which is quite difficult without app buildings.

---
forge version 3.5.4

**Comment by antoinevg** [comment]
This doesn't look like a problem with our side of things. 

Going by the error message it looks like your build scripts can't find the forge executable:

    ...
    /bin/sh: 1: forge: not found

**Comment by soemo** [comment]
Ok maybe that was not the best error log.But I can see the  [Errno 54] Connection reset by peer in that log

````
[ FAILED]Error: Command failed: native-android-staffbasePublicStore/ && forge --username XXX --password ######## build android
[   INFO] Forge tools version: 3.5.4
[   INFO] Update result: you already have the latest tools
[   INFO] Your Forge platform has been updated, downloading updated build instructions.
[   INFO] Fetching generation instructions for v2.8.6 into "/var/folders/ld/3_fjw82n1fz3ch2d6m8v3jtm0000gn/T/forge-templates-Ktafdj/.template"
[   INFO] Removing old templates if present
[   INFO] Using new templates
[   INFO] Running from build-tools
[   INFO] Update result: you already have the latest tools
[   INFO] Using generate_dynamic.buildtools for build
[   INFO] Comparing app assets against build cache
[   INFO] Your app configuration has changed since your last build of this platform, performing a remote build of your app. Once this is downloaded future builds will be faster.
[   INFO] no assets to inject
[   INFO] Starting new build
[   INFO] This could take a while, but will only happen again if you modify config.json
[  ERROR] Something went wrong that we didn't expect:
[  ERROR] [Errno 54] Connection reset by peer
[  ERROR] Please contact support@trigger.io
````

https://stackoverflow.com/questions/1434451/what-does-connection-reset-by-peer-mean

**Comment by antoinevg** [comment]
Argh, my apologies.

Since a few months ago there's been a recurring issue where Apple's servers are randomly refusing Xcode permission to sign builds until we log out and log in again on the build machines. (please don't ask me why Xcode has to talk to Apple's servers before signing builds)

So far we've been unable to get any acknowledgement from them that it's a problem or what the root cause may be.

I've bumped the build machines and things should be running again.

**Comment by soemo** [comment]
Thanks it is working again
