### ISSUE TITLE
Update Forge for Java >= 9 compatibility

### ISSUE THREAD

**Issue by antoinevg** [trigger-corp/forge#7]
Trying to run Forge under a Java 10 installation will throw exceptions such as:

    java.lang.NoClassDefFoundError: sun/misc/BASE64Encoder

This is caused by Oracle's decision to remove the sun.* packages with the release of Java 9 and subsequent Java platform versions.

More info: [Why Developers Should Not Write Programs That Call 'sun' Packages](https://www.oracle.com/technetwork/java/faq-sun-packages-142232.html)

**Describe the solution you'd like**

Identify affected components and replace usage of sun.* packages:

- [x] apk-signer.jar
    * apk-signer.jar depends on sdklib.jar 
    * sdklib.jar is deprecated
    * the BASE64Encoder reference is in sdklib.jar
    * sources: https://bintray.com/package/files/android/android-tools/com.android.tools.sdklib
- [x] Update Guava to latest (https://github.com/google/guava)
- [x] Clean out `android/ForgeCore/libs`

**Additional context**

* https://stackoverflow.com/questions/29692146/
* https://issuetracker.google.com/issues/62471410

**Comment by adrianpike** [comment]
So is this closed as a wontfix and we need to downgrade Java, or what? I'm on `Forge tools version 3.4.7` and unable to build for Android because of the aforementioned `BASE64Encoder` exception.

**Comment by antoinevg** [comment]
It depends!

As you can see above we've updated all of our code to no longer user the `sun.*` packages deprecated by Oracle.

You can test to see if this resolves your issue by upgrading to Forge `v2.8.x`:

https://trigger.io/docs/current/api/beta_release_notes.html

That said, if you're still seeing issues it will be because - last time we looked - Java >= 9 support for the Android SDK itself was rather spotty.
