### ISSUE TITLE
Android Forge build not working

### ISSUE THREAD

**Issue by soemo** [trigger-corp/forge#75]
Hello Antoine,

Since today we have the problem that we can not longer build our Android app by using forge.
Is there a known problem?
![2020-08-18-problem-with-android-build](https://user-images.githubusercontent.com/300618/90501821-3c61df80-e14d-11ea-92c9-0dcd12b0b5de.png)

**Comment by antoinevg** [comment]
My apologies, I've been doing some emergency maintenance work today which has reduced the number of build instances available and slowing things down.

If you just leave the builds running they'll complete on their own.

**Comment by frrob** [comment]
Hi @antoinevg ,
It seems we have the same issue again. We've been trying to build but nothing has been working for a couple of hours now (~ 4h). Could you be so kind and check if everything is up and running? 🙏 
![Bildschirmfoto 2020-10-14 um 18 06 31](https://user-images.githubusercontent.com/45992338/96015624-13598480-0e48-11eb-9914-038afa0c6b63.png)

**Comment by antoinevg** [comment]
I'm so embarrassed. This was 100% my carelessness for forgetting to restart the android build servers after the v2.9.1beta-4 release today. Things should be back up and running again. 🙈

**Comment by frrob** [comment]
Thank you for your quick response. Everything is back working! 🎉
