### ISSUE TITLE
Remote signing does not work with Apple Distribution certificates

### ISSUE THREAD

**Issue by rkusa** [trigger-corp/forge#78]
**Device information:**
 - Hardware: 
 - Operating System and Version: Ubuntu/Windows latest
 - Forge Platform version: v2.8.6

**App information:**

**To Reproduce**

1. Configure forge to use an `Apple Distribution` certificate (and not an `iPhone Distribution` certificate)
2. Package an iOS app (on everything other than a mac so that the remote signing is used)

**Expected behaviour**

App is signed successfully.

**Actual behaviour**

Signing fails with:

```
iPhone: no identity found
```

**Related information:**

With Xcode 11 Apple introduced [the new Apple Distribution certificates](https://developer.apple.com/documentation/xcode-release-notes/xcode-11-release-notes):

> Xcode 11 supports the new Apple Development and Apple Distribution certificate types. These certificates support building, running, and distributing apps on any Apple platform. Preexisting iOS and macOS development and distribution certificates continue to work, however, new certificates you create in Xcode 11 use the new types. Previous versions of Xcode don’t support these certificates. (45527608)

When building Trigger.io apps on macOS, `forge package ios` still works, since it executes `codesign` using the complete certificate name as specified in the `local_config.json`:

```
codesign --force --identifier ### --entitlements ### --sign 'Apple Distribution: YOUR NAME (12345)' device-ios.app
```

However, the remote signing instead executes:

```
codesign --keychain ### --force --identifier ### --entitlements entitlements.plist --sign iPhone app
```

Since `--sign iPhone` does not match `Apple Distribution: YOUR NAME (12345)`, the signing fails. Possible solutions are probably:

- use the certificate name from `local_config.json` during remote signing, or
- use `--sign Distribution` which should match both `iPhone Distribution` and `Apple Distribution`.

Thanks for your time! A fix would be highly appreciated 🙏

**Comment by antoinevg** [comment]
As of `v2.9.1beta-3` the remote signing service uses the identity string specified in the app `local_config.json` file:

https://trigger.io/docs/current/api/beta_release_notes.html

For older Forge platform versions it will fall back to using the partial identity string: `Distribution`.

A side-effect of this change is that older Forge platform versions (`< v2.9.1beta-3`) will no longer be able to sign app binaries using a development certificate.

**Comment by rkusa** [comment]
Thanks a lot for the fix 🙌
