### ISSUE TITLE
Upcoming Android app icon changes

### ISSUE THREAD

**Issue by janascheck** [trigger-corp/forge#8]
I was wondering if there are any changes on trigger.io regarding the upcoming restrictions for Android App icons (see the link below)?

https://android-developers.googleblog.com/2019/03/introducing-new-google-play-app-and.html?m=1

**Comment by antoinevg** [comment]
It doesn't look like this affects anything on the platform itself. 

It probably only affects the creation of icons that are to be uploaded to Google Play.
