### ISSUE TITLE
Forge not working for iOS

### ISSUE THREAD

**Issue by frrob** [trigger-corp/forge#88]
Hello Antoine,

Since today we have the problem that we cannot build apps for iOS.
The forge command does not finish after it was running for 2h.
Is there a known problem?
Maybe a relationship to this case? https://github.com/trigger-corp/forge/issues/48
Thanks for your support!

![Bildschirmfoto 2020-12-22 um 13 40 04](https://user-images.githubusercontent.com/45992338/102889960-df0fcf00-445b-11eb-9265-316289784541.png)

**Comment by antoinevg** [comment]
My apologies for taking so long to get back to you on this, I'm currently away from the office with limited Internet access.

It looks like it was indeed another case of #48 :-(

I've logged the machines back in and everything should be working again.

**Comment by frrob** [comment]
Thank you @antoinevg !
I can confirm that it's working again.
