### ISSUE TITLE
Unable to upload MP4 files from iOS

### ISSUE THREAD

**Issue by suthirram** [trigger-corp/forge#89]
**Device information:**
 - Hardware: iPhone XR
 - Operating System and Version: iOS14.1
 - Forge Platform version: v2.9.1

**App information:**

```
"platform_version": "v2.9.1",
"core": {
...
  "ios": {
    "device_family": "any",
    "package_name": "%ios_package_name%",
    "disable_web_storage_backup": true,
    "webview": "WKWebView"
  }
},
```

**To Reproduce**

1) Click on the add attachment icon
2) select "Video Library"
3) Choose a MP4 file to be uploaded( Screen recording from iPhone serves the purpose)

**Expected behaviour**
The user should be able to upload the video file of MP4 format from the video library as an attachment.

**Actual behaviour**

When the user tries to upload a mp4 file, error thrown as below:
``` 
Unknown client error 
No valid items selected  
false
```

**Related information:**
See the video for more context.
[Video Link](https://drive.google.com/file/d/1Lr0-4zIxXgUikvuPguNDA30neajgOJok/view?usp=sharing)

**Comment by antoinevg** [comment]
Thank you for the report, it does indeed not work for `.mp4` files!

Fixed in: trigger-corp/trigger.io-file@daf3363

Can you please bump your module version to check?

```
"file": {
    "version": "2.27"
},
```

**Comment by suthirram** [comment]
The fix works fine with iOS. 👍🏼
