### ISSUE TITLE
iOS:  Application becomes unresponsive when a larger video file is being uploaded from the video library

### ISSUE THREAD

**Issue by suthirram** [trigger-corp/forge#90]
**Device information:**
 - Hardware: iPhone XR
 - Operating System and Version: iOS 14.1
 - Forge Platform version: v2.9.1

**App information:**

```
"platform_version": "v2.9.1",
"core": {
...
  "ios": {
    "device_family": "any",
    "package_name": "%ios_package_name%",
    "disable_web_storage_backup": true,
    "webview": "WKWebView"
  }
},
```
**To Reproduce**

1. Click on the add attachment icon
2. Select "Video Library"
3. Select a larger video 

**Expected behaviour**
 
A window where the video compression status is shown and control navigates to original window and preview of the attachment is shown

**Actual behaviour**

The application looks as if it is frozen for a while until the preview is ready

**Related information:**

When the user attaches a larger video file from the library using `Add attachment -->Video library`, the control comes back to the original window and the application is frozen until the video is compressed and the preview is ready.

See the attached video for expected and actual behaviour
[Actual](https://drive.google.com/file/d/1uyRyFXe6-RwK3eyXghqX-hMV2ChI4HwU/view?usp=sharing)
[Expected](https://drive.google.com/file/d/1M5NCHhWhGF_DhqbbUjGZw2CI3LME_BoK/view?usp=sharing)

**Comment by antoinevg** [comment]
There's not much to be done about this I'm afraid.

As of iOS 14 the new Photos permissions changes have created a situation where we need to make a local copy of the Video in order for the WebView to have access to it. The freeze you're seeing is the time it takes to make that copy.

Hopefully a future release of iOS 14 will provide some kind of progress callback so we can display a progress bar.
