### ISSUE TITLE
didReceiveRemoteNotification not called in iOS when Trigger platform version is set to 2.9.1

### ISSUE THREAD

**Issue by arblitroshani** [trigger-corp/forge#91]
**Device information:**
 - Hardware: `iPhone 11`
 - Operating System and Version: `iOS 14.4`
 - Forge Platform version: `2.9.1`

**To Reproduce**

1. Build an iOS app using Trigger platform version 2.9.1 and Parse plugin.
2. Ensure app is running in the background.
2. Send push notification to the app.
2. Click on the push notification.

**Expected behaviour**
 
[`didReceiveRemoteNotification`](https://github.com/trigger-corp/trigger.io-parse/blob/master/inspector/ios-inspector/ForgeModule/parse_EventListener.m#L54) gets called with the notification payload, and `event.messagePushed` gets emitted.

**Actual behaviour**

`didReceiveRemoteNotification` does not get called when app is in the background.

**Related information:**

- Notification is handled properly when app is closed, because `application(didFinishLaunchingWithOptions:launchOptions)` is used.
- This bug did not happen when app was built with platform version `2.8`.
- We are using our own fork of Parse plugin with the following `manifest.json`
```javascript
{
    "changes": "...",
    "dependencies": {
        "bolts": {
            "minimum_version": "1.10.0",
            "maximum_version": "1.10.0"
        }
    },
    "description": "Parse.com configuration to enable push notifications.\n\nThe parse module uses the Parse.com SDK to allow for native push notifications.",
    "min_platform_version": "v2.9.1",
    "namespace": "parse",
    "platform_version": "v2.9.1",
    "version": "3.2"
}
```

**Comment by antoinevg** [comment]
Do you also observe this behavior with the Trigger.IO version of the parse module?

**Comment by arblitroshani** [comment]
Could reproduce with the latest version of `trigger-corp/trigger.io-parse`. 
Exactly the same behavior.

**Comment by antoinevg** [comment]
Thank you for the report! I was able to reproduce it on my side and track down the problem.

Can you please:

1. Update your platform version to:
```
"platform_version": "v2.9.2",
```

2. Update your parse module version to:
```    
"parse {
    "version": "3.3",
    ...
}
```

Please see the following commit if you need more details to bring your fork up to date:

trigger-corp/trigger.io-parse@756ec11

**Comment by arblitroshani** [comment]
Thanks for the quick fix Antoine!
Working ok for me too.
