### ISSUE TITLE
ERR_CLEARTEXT_NOT_PERMITTED with Android PDF viewer

### ISSUE THREAD

**Issue by daviddbal** [trigger-corp/forge#92]
I have discovered a problem with viewing PDF files after upgrading from platform 2.8 to 2.9.  On Android devices I am getting the following error:

Regular Android device: 

```
[Forge modal WebView error] net::ERR_CLEARTEXT_NOT_PERMITTED
Returned: {"event":"tabs.9B09A0F4-7DB1-4124-830C-C2332F046966.loadError","params":{"url":"http://undefined/?file=https%3A%2F%2Flocalhost%3A31929%2Fpermanent%2Fbc29901f-2d63-4295-b266-e5a0c896d9f0.MAR2021%20PK%20LEB_Combo.pdf#page=38","description":"net::ERR_CLEARTEXT_NOT_PERMITTED"}}
```

Kindle (notice blank url)
Returned: 

```
{"event":"tabs.406518F5-D213-41A5-BE2E-477D7FE91CFA.loadStarted","params":{"url":"about:blank"}}
```

Any tips on how to resolve this problem?

**Comment by antoinevg** [comment]
Newer Android webviews disallow non-https URL's. 

You have two options to resolve this:

1. Host your content on a `https://` URL with a valid SSL certificate.
2. Globally force the WebView to accept `http://` URL's by adding the following to the `flags` section of your `src/config.json`:

```
...
"platform_version": "v2.9.2",
"flags": {
    "android_uses_cleartext_traffic": true
}, ...
```

(It may also be a good idea to set up your `trusted_urls` section to only allow the specific http resources you will be accessing.)

re: Kindle behavior - it probably doesn't have a problem with http URL's but it probably also doesn't implement any PDF handling intents. (The Android WebView has never supported viewing PDF's and only some Android versions will know to spawn an external viewer)

**Comment by daviddbal** [comment]
I am following the second approach you suggested by adding the cleartext flag to true. I believe the first approach would require adding a local SSL cert, which I think is more complicated.  Now I'm getting this error:

Returned: {"event":"tabs.9A85DE72-0DA9-4D5B-BBE2-C14F8D1697E2.loadError","params":{"url":"http://undefined/?file=https%3A%2F%2Flocalhost%3A31929%2Fpermanent%2F66694e11-27f0-49f5-9894-d1a9372c4db7.MAR2021%20School_age%20LEB_Combo.pdf#page=40","description":"net::ERR_NAME_NOT_RESOLVED"}}

I don't know why the url contains undefined.  The file is stored in an AWS S3 bucket, which is referenced by https.  Is the http reference a way to access the file in local storage?

**Comment by antoinevg** [comment]
Hrmmm… I didn't pay close attention to the url but you're right, it makes little sense.

We no longer use `?file=` style URLs but I wonder if you're managing to hit some of the old filesystem URL normalization code?

If you're accessing something stored locally in your app on the device it should just look something like:

`https://localhost:31929/permanent/66694e11-27f0-49f5-9894-d1a9372c4db7.MAR2021 School_age LEB_Combo.pdf#page=40`

If it's hosted on S3 it should be something like:

`https://s3.amazonaws.com/path-to-bucket/your-file`

Do you have some code I can look at?

**Comment by daviddbal** [comment]
This is the html that renders the link.  The code works fine in the browser so the first block must be the problem.

```
<span ng-if="isPDFandNative(ev)">
  <a ng-click="showPDF(ev)" >
    <span class="glyphicon glyphicon-link"></span>
    <span class="streamLabel" ng-bind="ev.label"></span>
  </a>
</span>
<span ng-if="!isPDFandNative(ev)">
  <a ng-if="ev.url.startsWith('kidreports://')" ng-click="goTo(format(ev.url))">
    <span class="glyphicon glyphicon-link"></span>
    <span class="streamLabel" ng-bind="ev.label"></span>
  </a>
  <a ng-if="!ev.url.startsWith('kidreports://')" ng-href="{{format(ev.url)}}" target="{{getTarget(ev.url)}}">
    <span class="glyphicon glyphicon-link"></span>
    <span class="streamLabel" ng-bind="ev.label"></span>
  </a>
</span>
```


Here's showPDF
```
        scope.showPDF = function(ev) {
          $pdf.open(ev.url);
        }
```

Here's open:

```
    svc.open = function(url) {
      if ( $native.isNative() ) {
        _open(url);
      } else {
        window.open(url)
      }
    }

  function _open(baseurl) {
    var pdfurl = baseurl.replace("https://s3.amazonaws.com/kidreports-media/public/pdfjsweb/viewer.html?file=", "");
    var page = "";
    var pageidx = pdfurl.indexOf("#page=");
    if ( pageidx > -1 ) {
      page = pdfurl.substr(pageidx);
      pdfurl = pdfurl.substr(0, pageidx);
    }
    pdfurl = pdfurl.replace(/\s/g, '%20');

    forge.file.getLocal('pdfjsweb/viewer.html', function (f) {
      var uri = typeof(forge) != 'undefined' && forge.httpd ? forge.httpd.normalize(f.uri) : f.uri;
      //var uri = f.uri;
      forge.prefs.get(pdfurl, function (d) {
        if (d) {
          d = typeof(forge) != 'undefined' && forge.httpd ? forge.httpd.normalize(d) : d;
          _openPDF(uri, d, page);
        } else {
          _savePDF(uri, pdfurl, page, baseurl);
        }
      })
    })
  }
`
```

**Comment by daviddbal** [comment]
For the browser I get a link in the format you describe.  If I want to skip the local storage I could just use that format, right?  I'm not sure that's desirable for our customers, but it better than dead links.

**Comment by antoinevg** [comment]
Ah okay, it's making a bit more sense now -  it looks like you're running a HTML/Javascript PDF viewer (`pdfjsweb/viewer.html`) which is hosted in the local webview and then (maybe?) passing the S3 url to it?

Either way I'd start by removing all references to `forge.httpd` and `forge.httpd.normalize` and seeing what things look like then.

**Comment by daviddbal** [comment]
What you do you mean remove forge.httpd and forge.httpd.normalize?  I know in version 2.8 httpd was removed and put into the core runtime by default but I thought the code didn't need to change.  Am I wrong?

**Comment by antoinevg** [comment]
In theory the `forge.httpd.*` namespace should just be "pass-through" now but, to be safe, you can remove the calls and just use the file object returned by `file.getLocal()` directly.

Also, while we're about it - the file object returned by `file.getLocal()` no longer supports direct access to the `file.uri` component. (This was a horrible hack anyway, it should never have been needed)

…and there has been some method renames.

So, *thinks.for.a.moment*… to modernize what you have:

1. Use `forge.file.getFileFromSourceDirectory(path, success, error)` instead of `forge.file.getLocal()`
2. Instead of accessing the `file.uri` component directly, use `forge.file.getScriptURL(file, success, error)`

So something like:

```
forge.file.getFileFromSourceDirectory('pdfjsweb/viewer.html', function (file) {
    forge.file.getScriptURL(file, function (url) {
        // do stuff with the url
    });
});
```

More info: https://trigger.io/modules/file/current/docs/index.html
