### ISSUE TITLE
Local Storage Problem with 2.9 Platform Upgrade

### ISSUE THREAD

**Issue by daviddbal** [trigger-corp/forge#93]
I'm seeing a problem with saving pdf files to local storage on Android and retrieving them afterwards. This problem started after upgrading to platform 2.9.  The pdf viewer opens but produces an error ("Unexpected server response") with the local storage uri.  I know the problem is limited to local storage because if I bypass the local storage code and provide a direct link to the pdf file stored in S3 the file opens correctly.  I have a requirement to use local storage as a file cache.

I've noticed some differences with the uri from the 2.8 version and the new 2.9 version.  Are the changes intentional and correct? 
 Here are some examples:

2.8 uri:  `https://localhost:31929/file?uri=file%3A%2F%2F%2Fstorage%2Femulated%2F0%2FAndroid%2F[…]ent%2Ffiles%2FDownload%2F9e929f6f-5b1e-4d16-8298-c5daf7a3930e`

2.9 uri: `https://localhost:31929/temporary/b6d13c08-72fd-4c3f-8f3f-96b5b5fe2296.APR2021%20School_Age%20LEB_Combo.pdf'`

Here is the relevant source code:

```javascript
function _open(baseurl) {
    //    openAdvanced2(baseurl); // bypasses local storage
    var pdfurl = baseurl.replace("https://s3.amazonaws.com/kidreports-media/public/pdfjsweb/viewer.html?file=", "");
    var page = "";
    var pageidx = pdfurl.indexOf("#page=");
    if ( pageidx > -1 ) {
        page = pdfurl.substr(pageidx);
        pdfurl = pdfurl.substr(0, pageidx);
    }
    pdfurl = pdfurl.replace(/\s/g, '%20');

    forge.file.getFileFromSourceDirectory('pdfjsweb/viewer.html', function (f) {
        forge.file.getScriptURL(f, function(uri) {
            forge.prefs.get(pdfurl, function (d) {
                forge.logging.log("URI:" + uri + " |d| " + d + " |pdfurl| " + pdfurl);
                if (d) {
                    d = d.replace(/\s/g,'%20');
                    _openPDF(uri, d, page);
                } else {
                    _savePDF(uri, pdfurl, page, baseurl);
                }
            })
        })
    })
}

function _openPDF(uri1, uri2, page) {
    forge.logging.log("Opening:"+uri1 + "|" + uri2);
    openAdvanced2(uri1 + "?file="+encodeURIComponent(uri2)+page);
}

function _savePDF(uri1, saveuri, page, originalURI) {
    $timeout(function() {$model.isRefreshing=true;} );
    //      saveuri = saveuri.replace(/\s/g,'%20');
    forge.logging.log("saveuri:" + saveuri);
    forge.file.cacheURL(saveuri, function(f2) {
        $timeout(function() {$model.isRefreshing=false;} );
        forge.file.getScriptURL(f2, function(uri2) {
            forge.logging.log("URI2:" + uri2);
            forge.prefs.set(saveuri, uri2, function(s) {
                //_openPDF(uri1, uri2, page);
                _open(originalURI)
            })
        })
    })
}

function openAdvanced2(theUrl) {
    forge.tabs.openAdvanced({
        url: theUrl,
    }, function (modal) {
        modal.loadFinished.addListener(function (obj) {
        });
        modal.loadError.addListener(function (obj) {
        });
        modal.closed.addListener(function () {
        });
    });
}
```

Here are some additional questions than can help me troubleshoot this problem.
Is there a way for me to check the files that are in local storage?

Can I confirm the local storage uri I'm using is correct and actually points to a file?

**Comment by antoinevg** [comment]
1. The format for file objects changed with the `v2.9` release, so the second example you have is in the correct format for usage with platform versions `v2.9.x` and higher. 

2. You can check whether a file exists with: [`forge.file.exists(file, success, error)`](https://trigger.io/modules/file/current/docs/index.html#forgefileexistsfile-success-error) 

3. Mobile storage tends to not follow traditional filesystem semantics so we never provided a general file listing API. What you can do in the meantime though maybe is to use [`adb shell`](https://stackoverflow.com/questions/16796432/how-to-list-all-the-files-in-android-phone-by-using-adb-shell) or some other software to attach to your device directly and get a directory listing for the app:
>  -  The `file.cacheURL` API uses the `/temporary` endpoint to store files which gets its [physical location](https://gist.github.com/lopspower/76421751b21594c69eb2) from the native [`Context.getCacheDir()`](https://developer.android.com/reference/android/content/Context#getCacheDir()) Android API like so: 
>      `Path cacheDirectory = Paths.get(ForgeApp.getActivity().getCacheDir().getPath(), "forgecore");`
>  - On most of my devices this maps to something like:
>       `/data/data/<package_name>/cache/forgecore`

**Comment by daviddbal** [comment]
I found that the file exists with the function you provided.  However, it still won't open in the pdf viewer (I get a server error).  The link to S3 does open the pdf correctly.  Is there anything different between the file in local storage and the direct link?

Also, I only get an error on the device on the pdf viewer.  I don't see any errors in the console.  Here are the relevant logs:

```
[   INFO] 04-15 09:28:17.277  9239  9358 I Forge   : [FORGE] 'exits:true'
[   INFO] 04-15 09:28:17.301  9239  9239 D Forge   : Returned: {"content":true,"callid":"D0A73E68-EF72-45EB-A6D5-8B6CCA554676","status":"success"}
[   INFO] 04-15 09:28:17.304  9239  9373 I Forge   : [FORGE] 'URI2:https://localhost:31929/temporary/5305126e-23c8-4c5f-bf33-3fb37b18c55b.MAR2021 School_age LEB_Combo.pdf'
[   INFO] 04-15 09:28:17.305  9239  9372 D Forge   : Native call prefs.set with task.params: {"key":"https://s3.amazonaws.com/kidreports-media/documents/af890cqw48jcmclahkluxdt89ujnpy8h7s4m0aweq-k490um-4qfAWZKZDKJ89/cni/x39b8vaj3cxh934jgszkldjg89/March%202021/School%20Age/MAR2021%20School_age%20LEB_Combo.pdf","value":"\"https://localhost:31929/temporary/5305126e-23c8-4c5f-bf33-3fb37b18c55b.MAR2021 School_age LEB_Combo.pdf\""}
[   INFO] 04-15 09:28:17.306  9239  9239 D Forge   : Returned: {"content":"https://localhost:31929/temporary/5305126e-23c8-4c5f-bf33-3fb37b18c55b.MAR2021 School_age LEB_Combo.pdf","callid":"5C9D958F-EACB-4253-A8DD-E1F10BCD9695","status":"success"}
[   INFO] 04-15 09:28:17.319  9239  9374 D Forge   : Native call file.getFileFromSourceDirectory with task.params: {"resource":"pdfjsweb/viewer.html"}
[   INFO] 04-15 09:28:17.321  9239  9239 D Forge   : Returned: {"content":null,"callid":"E8625E33-3E1F-4107-88BC-E1CB91EB83E7","status":"success"}
[   INFO] 04-15 09:28:17.323  9239  9358 D Forge   : Native call file.getScriptURL with task.params: {"file":{"endpoint":"/src","resource":"pdfjsweb/viewer.html"}}
[   INFO] 04-15 09:28:17.326  9239  9239 D Forge   : Returned: {"content":{"endpoint":"/src","resource":"pdfjsweb/viewer.html"},"callid":"897D6032-3C8D-4E3F-BE7C-C096284A75D9","status":"success"}
[   INFO] 04-15 09:28:17.328  9239  9373 D Forge   : Native call prefs.get with task.params: {"key":"https://s3.amazonaws.com/kidreports-media/documents/af890cqw48jcmclahkluxdt89ujnpy8h7s4m0aweq-k490um-4qfAWZKZDKJ89/cni/x39b8vaj3cxh934jgszkldjg89/March%202021/School%20Age/MAR2021%20School_age%20LEB_Combo.pdf"}
[   INFO] 04-15 09:28:17.331  9239  9239 D Forge   : Returned: {"content":"https://localhost:31929/src/pdfjsweb/viewer.html","callid":"CBDEC027-0476-4ABC-AF6C-C5257FED1F73","status":"success"}
[   INFO] 04-15 09:28:17.333  9239  9372 I Forge   : [FORGE] 'URI:https://localhost:31929/src/pdfjsweb/viewer.html |d| https://localhost:31929/temporary/5305126e-23c8-4c5f-bf33-3fb37b18c55b.MAR2021 School_age LEB_Combo.pdf |pdfurl| https://s3.amazonaws.com/kidreports-media/documents/af890cqw48jcmclahkluxdt89ujnpy8h7s4m0aweq-k490um-4qfAWZKZDKJ89/cni/x39b8vaj3cxh934jgszkldjg89/March%202021/School%20Age/MAR2021%20School_age%20LEB_Combo.pdf'
[   INFO] 04-15 09:28:17.334  9239  9374 I Forge   : [FORGE] 'Opening:https://localhost:31929/src/pdfjsweb/viewer.html|https://localhost:31929/temporary/5305126e-23c8-4c5f-bf33-3fb37b18c55b.MAR2021%20School_age%20LEB_Combo.pdf'
[   INFO] 04-15 09:28:17.336  9239  9358 D Forge   : Native call tabs.open with task.params: {"url":"https://localhost:31929/src/pdfjsweb/viewer.html?file=https%3A%2F%2Flocalhost%3A31929%2Ftemporary%2F5305126e-23c8-4c5f-bf33-3fb37b18c55b.MAR2021%2520School_age%2520LEB_Combo.pdf#page=33"}
```

Any tips?

**Comment by antoinevg** [comment]
Hrmmm…

There shouldn't be a difference between remote files and what we download. You could take a look using [`forge.file.string`](https://trigger.io/modules/file/current/docs/index.html#forgefilestringfile-success-error) if you wanted to be sure though.

What happens if you stick the `pdf` file in your source directory and try open it with the viewer from there?

Otherwise I'm pretty stumped, you may need to dig deeper into what `viewer.html` itself is doing to figure out why it doesn't like what it's being served?
