### ISSUE TITLE
Can we build the new aab format with TriggerIO  - Android App Bundle is required for new apps from August 2021

### ISSUE THREAD

**Issue by soemo** [trigger-corp/forge#94]
Hello, 

On the Google timeline is the point [New apps and games must publish with the Android App Bundle](https://developer.android.com/distribute/play-policies#RequirementForNewApps)

> From August 2021, all new apps and games will be required to publish with the Android App Bundle format. New apps and games must use Play Asset Delivery or Play Feature Delivery to deliver assets or features that exceed a download size of 150MB. Private enterprise apps are not subject to this requirement.

Now the question is, can we build the aab format with the current TriggerIO /forge version 2.9.2?

Additional information
* [New Android App Bundle and target API level requirements in 2021](https://android-developers.googleblog.com/2020/11/new-android-app-bundle-and-target-api.html)
* [About Android App Bundles](https://developer.android.com/guide/app-bundle)

**Comment by soemo** [comment]
Hello Antoine,

I saw you add the AndroidAppBundle to the next milestone. Can you tell me a ~ due date?

And I have another question to a change from Google in August
> Apps must target API level 30
When you upload an app bundle or APK, it needs to meet Google Play’s target API level requirements. By August 2021, new apps must target at least Android 11 (API level 30). By November 2021, all apps that are being updated must target at least Android 11 (API level 30). 

I read this blog post with a list of changes which another team has to made for this SDK update.
https://eng.wealthfront.com/2021/05/05/targeting-android-sdk-30/
Therefore the question to you: Do you see problems in the same areas for the trigger forge apps?

**Comment by antoinevg** [comment]
Android App Bundle support - you can expect the first beta of v2.10.x early-ish July. It's not great that Google are scheduling this to happen before the final release of Android 12. :-/

re: Target API level - we've been targeting API level 30 since September last year so you're good to go.

**Comment by jreimone** [comment]
@antoinevg is there a chance to narrow the publication date of v2.10.x a bit down?

**Comment by soemo** [comment]
Hello @antoinevg, 

Today I tried to increase the Android API level to 30 and got this error
>[  ERROR] Forge API call to app/707ecebf679343e7921a5925591966ab/build went wrong: Value u'30' for field 'minimum_version' is not in the enumeration: [u'14', u'15', u'16', u'17', u'18', u'19', u'20', u'21', u'22', u'23', u'24', u'25', u'26']

I used the forge version 2.9.2 from March 2021 and the last one 2.9.3 
But you wrote it should work.
> re: Target API level - we've been targeting API level 30 since September last year so you're good to go.

Can you please check if it really works for you?

**Comment by antoinevg** [comment]
`minimum_version` does not set the Android API level. Rather it limits what the minimum required Android API support is required from a device that wants to run your app. 

Unless you have a very specific use case in mind it's best to leave this setting alone.

The Android compile & target SDK versions cannot be set as they need to be hardcoded for each release.

**Comment by soemo** [comment]
Thanks for the clarification. 
That means I have nothing to change. An app build with triggerIO forge version 2.9.2 is ready to work with Android API level 30?

**Comment by antoinevg** [comment]
I've pushed Android App Bundle support to platform `v2.9.4` in  `staging`:

https://trigger.io/docs/current/api/release_notes.html

Could you please give this a go on your side and let me know if you run into any issues?

Steps:

1. Bump your app's `platform_version` to `v2.9.4`
2. `forge build android`
3. `forge package android`

You should now have an `aab` file in your app's `release` directory.

---

#### NOTE

One thing to watch out is your signing certificate. Android App Bundles need to be signed with a certificate that supports:

* Signature Algorithm: `SHA256withRSA`
* Digest Algorithm: `SHA-256`

Specifically, the error message to watch out for with older certificates is:

```
[   INFO] Creating Android .aab file for target: android
[   INFO] Using java: /usr/bin/java
[   INFO] Using Android SDK: /Users/antoine/.forge/darwin/Android/sdk
[   INFO] Using jarsigner: /usr/bin/jarsigner
[   INFO] creating android app bundle file
[   INFO] signing android app bundle file
[  ERROR] Failed when running /usr/bin/jarsigner: jarsigner error: java.lang.IllegalArgumentException: key algorithm not compatible with signature algorithm
```

I had to generate a new certificate for myself in order to get it to run.

It's unclear to me what the exact situation is vis-a-vis using old vs new certificates with the switch to AAB.

It may also be that the best option would be for us to NOT sign AAB bundles during the build process at all and rather have our customers do it manually depending on what Google needs.

Either way, I'm open to feedback and suggestions!

**Comment by soemo** [comment]
Thanks, we will try it out today

**Comment by staust** [comment]
Hey,
some input from my POV here.
We can not change the key store files for existing apps as google does not support this. So in any case we need to find a way to support the current keystore files. Also I already got a .aab in hand for one of our apps some time ago. Currently I dont know how this was build just know it is possible. I try to get some insights how this was done.
In the mean time you could try to check the jdk and sdk versions and try different ones? Maybe also using the **APK-signer** instead of JAR-signer. E.g. back in time we already observed that keystore files generated with openjdk 16 are not working correctly:
```
java -version
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment (build 16.0.1+9)
OpenJDK 64-Bit Server VM (build 16.0.1+9, mixed mode)
```
but java version 11 was working with the same command:
```
java -version
java version "11.0.6" 2020-01-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.6+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.6+8-LTS, mixed mode)
```

**Comment by frrob** [comment]
Hello Antoine,

Thank you for providing us the update of the toolkit.

During testing, we found out that we are running into the issues you have already described.

We are currently building apps with a keystore that does not support these requirements.

We can not change the keystore files for existing apps as Google does not support this. So in any case we need to find a way to support the current keystore files.

For our newer apps we already exchanged the keystore files.

We found out that keystore files generated with openjdk 16 are not working correctly:

`java -version
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment (build 16.0.1+9)
OpenJDK 64-Bit Server VM (build 16.0.1+9, mixed mode)`

but java version 11 was working with the same command:
`java -version
java version "11.0.6" 2020-01-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.6+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.6+8-LTS, mixed mode)`

Can you please check if using different versions of the jdk and sdk would resolve the problem?

**Comment by frrob** [comment]
Hi @antoinevg ,
Please, could you give us a quick update on this?
We are currently blocked building apps using an old certificate.

**Comment by antoinevg** [comment]
I've added a couple new `local_config.json` options.

The first thing you can try is to set the signature and digest algorithms to something that matches your key. Older Android keys used SHA-1.

So try this:

```
...
"android": {
    "profiles": {
        "DEFAULT": {
            "keystore": "/path/to/your//android.keystore",
            "keypass": "<your key password>",
            "storepass": "<your keystore password>",
            "keyalias": "<your key alias>",
            "sigalg": "SHA1withDSA",               <== add this
            "digestalg": "SHA-1"                   <== and add this
        }
    },
...
```

You can also try signing your aab's manually by adding the `dontsign` option:

```
...
"android": {
    "dontsign": true,          <== add this
    "profiles": {
        "DEFAULT": {
            "keystore": "/path/to/your//android.keystore",
            "keypass": "<your key password>",
            "storepass": "<your keystore password>",
            "keyalias": "<your key alias>",
        }
    },
...
```

This will generate an AAB in your `releases/` directory that hasn't been signed and which you can then try signing yourself using jarsigner and your own parameters etc.

ps. do remember you'll need to invalidate your build before these changes will be picked up - so e.g. add the `parameters` module to your app, add an arbitrary value and rebuild before trying to run `package` again.

**Comment by soemo** [comment]
~~Hello @antoinevg~~ 
~~Thanks for the update and the new options. I tried it out with our existing key an run into this error during the Anroid packaging~~

````
[  ERROR] Failed when running /usr/bin/java: Failed to load signer "signer #1"
java.io.IOException: DerInputStream.getLength(): lengthTag=111, too big.
        at java.base/sun.security.util.DerInputStream.getLength(DerInputStream.java:251)
       
````

~~I added the two new options an we have the `parameters` module in place with a new added value~~


~~Any idea?~~

**Comment by antoinevg** [comment]
I'm guessing your error is something unrelated because it happened during APK signing and the new options only apply to AAB signing.

**Comment by soemo** [comment]
> I'm guessing your error is something unrelated because it happened during APK signing and the new options only apply to AAB signing.

You are right. It was an error in my setup. Now I'm able to build an apk and aab file with the orig keystore file and triggerIO 2.9.4.
Nice.

Now we need to test the aab upload to the Play store

**Comment by antoinevg** [comment]
Holding thumbs! Please let me know how it goes.

**Comment by soemo** [comment]
Hi @antoinevg ,

we were able to submit an .aab test app file and it passed the review.
But we changed your two settings to
> "sigalg": "SHA256withDSA",
   "digestalg": "SHA-256"
   
and for apps with a newer key we need to change the sigalg option too
>  "sigalg": "SHA256withRSA"

So from our side it is working.

**Comment by antoinevg** [comment]
Awesome @soemo, thank you for letting me know!

**Comment by soemo** [comment]
Hi @antoinevg, do you know when you set the version 2.9.4 as stable/final?

**Comment by antoinevg** [comment]
You can treat is as final, I just haven't had a chance to update the release page.
