### ISSUE TITLE
Error: Provisioning profile "iOS Team Provisioning Profile: " doesn't support the In-App Purchase capability

### ISSUE THREAD

**Issue by frrob** [trigger-corp/forge#97]
Hello @antoinevg,

during running `forge` we get the following error:
```
Build settings from command line:
    EXECUTABLE_NAME = Forge
    SDKROOT = iphoneos14.2

Build settings from configuration file '/private/tmp/tmpILPvTy/ios/app/fix_simulator_arch.xcconfig':
    EXCLUDED_ARCHS = $(inherited) $(EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_$(EFFECTIVE_PLATFORM_SUFFIX)__NATIVE_ARCH_64_BIT_$(NATIVE_ARCH_64_BIT))
    EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64 = arm64 arm64e armv7 armv7s armv6 armv8

note: Using new build system
note: Planning build
note: Constructing build description
error: Provisioning profile "iOS Team Provisioning Profile: " doesn't support the In-App Purchase capability. (in target 'ForgeInspector' from project 'ForgeInspector')
warning: MobileCoreServices has been renamed. Use CoreServices instead. (in target 'ForgeInspector' from project 'ForgeInspector')
warning: AddressBook is deprecated. Consider migrating to Contacts instead. (in target 'ForgeInspector' from project 'ForgeInspector')
warning: AddressBookUI is deprecated. Consider migrating to ContactsUI instead. (in target 'ForgeInspector' from project 'ForgeInspector')

* BUILD FAILED **


[   INFO] 2021-08-04 08:01:52,829 -- cleaning up source directories
[  ERROR] 2021-08-04 08:01:52,829 -- Xcode error

Fatal error: this.async is not a function
```

We haven't changed anything on our end of the setup. Have there been any updates made on your side that would lead to this?

Thanks for your support!

**Comment by antoinevg** [comment]
Was this from the builds you ran during the night?

If so, can you please try running them again?

We provisioned one of the new M1 Macs into the build farm yesterday and this morning I saw a bunch of build errors from your apps.

I looked into it and it seems that the M1 doesn't like the `parse`, `sb_parse` or the Staffbase `utils` module for some reason, even running under Rosetta. We've limited it to do v2.10beta-* builds for now until we can resolve this.

Otherwise, if you're still getting an error can you please provide a `src/config.json` I can use to replicate it? Thanks!

**Comment by antoinevg** [comment]
Ah, I can still replicate this under the older build machine. 

Suspect more certificate/entitlement weirdness from Apple. Will keep you posted.

**Comment by antoinevg** [comment]
Okay, I think we're good again. Can you try on your side?

Please let me know how it goes.

**Comment by frrob** [comment]
Unfortunately, we're still seeing issues.
forgeVersion = 'v2.9.2' is working
forgeVersion = 'v2.9.4' is not working

**Comment by antoinevg** [comment]
Whoo boy, okay - touch wood - now it should work for all the v2.9.x releases.

**Comment by frrob** [comment]
Thanks, @antoinevg ,
whatever you did, it worked :-)
