### ISSUE TITLE
App Icon and temporary background image are not branded in aab file format

### ISSUE THREAD

**Issue by frrob** [trigger-corp/forge#98]
Hello @antoinevg , 
We are experiencing a major issue where images are not built in correctly.

Building the aab file format, the app icon, and a temporary background icon, that appears quickly before the splash screen, are showing the trigger.io forge icons.

We were able to reproduce this only in the new Android App Bundle format.
The apk file format seems not affected.

We appreciate your help and looking forward to your input.

![Screen Shot 2021-08-30 at 17 59 32](https://user-images.githubusercontent.com/45992338/131462334-3ba5f835-3b14-48c1-8b27-005b7e83011a.png)
![Screen Shot 2021-08-31 at 09 38 37](https://user-images.githubusercontent.com/45992338/131462563-ce2679dc-4858-480c-aa91-40b7be4b7cc2.png)

**Comment by frrob** [comment]
Hello @antoinevg ,
we are still experiencing this major issue.
We are currently blocked in providing our customers with new apps.
Since it seems, that you are taking a look into this issue, could you give us some insights / status about the issue?
Thanks in advance.

**Comment by antoinevg** [comment]
Still researching, I'll let you know the second I have some information to share.

**Comment by antoinevg** [comment]
It looks like resource files aren't being populated as they should for the Android App Bundle builds.

I've pushed a workaround to:

    "platform_version": "v2.9.5"

Can you please give it a go and let me know?

Thanks!

**Comment by soemo** [comment]
Hi Antoine we see the correct images in the aab bundle now

**Comment by soemo** [comment]
Hello @antoinevg 
when do you make the 2.9.5 version stable?

**Comment by antoinevg** [comment]
I've pushed it to release, you're good to go!

https://trigger.io/docs/current/api/release_notes.html
